# Generated by Django 5.2.8 on 2026-02-05 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll_no', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('course', models.CharField(max_length=40)),
                ('phone_no', models.BigIntegerField()),
            ],
        ),
    ]
